import type { WeatherOverlayPoint } from "@/types/weather-data";

export const WEATHER_OVERLAY_POINTS: WeatherOverlayPoint[] = [
  {
    id: "seoul-current",
    countryCode: "KOR",
    countryName: "대한민국",
    label: "서울",
    latitude: 37.5665,
    longitude: 126.978,
    temperature: 22,
    condition: "cloudy",
    updatedAt: "Mock now",
  },
  {
    id: "tokyo-current",
    countryCode: "JPN",
    countryName: "일본",
    label: "도쿄",
    latitude: 35.6762,
    longitude: 139.6503,
    temperature: 25,
    condition: "rainy",
    updatedAt: "Mock now",
  },
  {
    id: "paris-current",
    countryCode: "FRA",
    countryName: "프랑스",
    label: "파리",
    latitude: 48.8566,
    longitude: 2.3522,
    temperature: 18,
    condition: "sunny",
    updatedAt: "Mock now",
  },
  {
    id: "new-york-current",
    countryCode: "USA",
    countryName: "미국",
    label: "뉴욕",
    latitude: 40.7128,
    longitude: -74.006,
    temperature: 20,
    condition: "foggy",
    updatedAt: "Mock now",
  },
  {
    id: "los-angeles-current",
    countryCode: "USA",
    countryName: "미국",
    label: "로스앤젤레스",
    latitude: 34.0522,
    longitude: -118.2437,
    temperature: 28,
    condition: "sunny",
    updatedAt: "Mock now",
  },
  {
    id: "london-current",
    countryCode: "GBR",
    countryName: "영국",
    label: "런던",
    latitude: 51.5072,
    longitude: -0.1276,
    temperature: 16,
    condition: "rainy",
    updatedAt: "Mock now",
  },
  {
    id: "sydney-current",
    countryCode: "AUS",
    countryName: "호주",
    label: "시드니",
    latitude: -33.8688,
    longitude: 151.2093,
    temperature: 19,
    condition: "cloudy",
    updatedAt: "Mock now",
  },
  {
    id: "sao-paulo-current",
    countryCode: "BRA",
    countryName: "브라질",
    label: "상파울루",
    latitude: -23.5558,
    longitude: -46.6396,
    temperature: 24,
    condition: "stormy",
    updatedAt: "Mock now",
  },
];
